language: python
group: travis_latest
cache: pip
python:
  - '3.6'

branches:
  only:
    - main

os:
  linux

env:
  global:
  - secure: "lxsAxsZ8ETcpmBjQBNb4HRBqU6zQ9fB+WGCHFt9n7jer2ifXN1he22JZMPTEnMcHn+RkY5GmgOfPVkn5VkL9ffklMKJCfDlhh4XRXTUJOUSRqZXA63qZBXCPBtEqHResRQmo2T6vXESv2FJ4Ax+r0s6LLMqDgad8uiI4WcS7iAkySQ0oIQL0yfQehviCN8JJl9ZNtbkDOTEeeCPpxAT66X4hJHmnThNW9zOsFMW3lYsLljqZLI1j8dqwqj8nCA2pd7k7QgQ4V0jqfWRxKv79FSHsV5NzBP+wDVc3HCRSpyMkTvdsn4c5wXTT4QE8l9R8UPE7vfjRqe9HqlgzmHvCf5LJkWDkMcjM5hGG4nJh5F4/y0OLQsAEemmN9oo/LpuB/Zz3dl8DSNtM5CDzc38L9XIPv718YL3zGhgR5x9Rl30oGBHWQwNXDcbspNMiNv65PH329Qp+CYaTfyce+0qepJEvmwvOJ0H88PRDilTAC81+U42OvjYSkMmzceenOrmxkXLdLDdj/yJWpbmR5hyGur/EYDgv8CgkpdNV0HP6ZNTgQ7AVLL2qw8OYTmkRhP3X3K/o+KByTKwifMi5i/o+sgotFiQtNV7IBAUuyzk+5x9fcj8mFiDy2jTVsN0Jh5YiXVhUVAtWyTU52HAdDvWPT1Tz1aTbB7iCQVOFbiEmt08="
  - SPHINX_DIR=docs/
  - HTML_DIR=docs/build/html
  - PYTHON_VERSION=3.6
  - CONDA_DEPENDENCIES="jupyter_contrib_nbextensions nglview sphinx ipywidgets MDAnalysis MDAnalysisTests plotly"
  - CONDA_CHANNELS='defaults conda-forge plotly'
  - PIP_DEPENDENCIES="sphinx_rtd_theme sphinx-sitemap nbsphinx ipython tabulate sphinxcontrib-bibtex pybtex msmb_theme==1.2.0"
  - CYTHON_TRACE_NOGIL=1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y pandoc


install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - jupyter-nbextension enable nglview --py --sys-prefix
  - conda list
  
script:
  - make -C ${SPHINX_DIR} html && touch ${HTML_DIR}/.nojekyll
  - echo "nb.minium.com.au" > ${HTML_DIR}/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: "${HTML_DIR}"
  on:
    branch: main

